from procgame.dmd import Animation, AnimatedLayer, font_named

class AssetLoader(object):
    """An asset manager inspired by SkeletonGame.AssetManager"""

    def __init__(self, game):
        self.game = game
        self.animations = {}
        self.fonts = {}

    def load_assets(self, curr_file_path):

        animations_files = [
            {'key': 'cityscape', 'file': 'cityscape.dmd', 'repeat':True, 'frame_time':2},
            {'key': 'Splash', 'file': 'Splash.dmd', 'holdLastFrame':True, 'frame_time':1},
            {'key': 'darkjudges', 'file': 'darkjudges.dmd', 'repeat':True, 'frame_time':4},
            {'key': 'longwalk', 'file': 'longwalk.dmd', 'frame_time':7},
            {'key': 'blackout', 'file': 'blackout.dmd', 'frame_time':3},
            {'key': 'dredd_shoot_at_sniper', 'file': 'dredd_shoot_at_sniper.dmd', 'frame_time':5},
            {'key': 'blockwars', 'file': 'blockwars.dmd', 'repeat':True, 'frame_time':3},
            {'key': 'jdpeople', 'file': 'jdpeople.dmd', 'frame_time':1},
            {'key': 'cows', 'file': 'cows.dmd', 'frame_time':1},
            {'key': 'scopeandshot', 'file': 'scopeandshot.dmd', 'frame_time':1},
            {'key': 'gun_powerup', 'file': 'gun_powerup.dmd', 'holdLastFrame':True, 'composite_op':'blacksrc', 'frame_time':7},
            {'key': 'bike_across_screen', 'file': 'bike_across_screen.dmd', 'frame_time':3},
            {'key': 'bikeacrosscity', 'file': 'bikeacrosscity.dmd', 'frame_time':5},
            {'key': 'extra ball', 'file': 'extra_ball.dmd', 'frame_time':1}
        ]

        lampshow_files = [
            {'key': 'advance_level', 'file': 'crimescene_advance_level.lampshow'},
            {'key': 'attract0', 'file': 'attract_show_horiz.lampshow'},
            {'key': 'attract1', 'file': 'attract_show_vert.lampshow'},
            {'key': 'jackpot', 'file': 'jackpot.lampshow'},
            {'key': 'shot_hit', 'file': 'flashers_only.lampshow'},
        ]

        music_files = [
            {'key': 'background', 'file': 'brainsDarkMelody(161).aif'},
            {'key': 'ball_launch', 'file': 'introloop(161).aif'},
            {'key': 'mode', 'file': '40 Second guitar solo.aif'},
            {'key': 'mode', 'file': '55 second loopable -- Sonya.aif'},
            {'key': 'mode', 'file': '105 second loopable -- Sisyphus.aif'},
            {'key': 'pursuit', 'file': '105 second loopable -- Sisyphus.aif'},
            {'key': 'multiball', 'file': 'Heroes and Angels -- Loopable.aif'},
        ]

        effects_files = [
            {'key': 'block_war_target', 'file': 'DropTarget.ogg'},
            {'key': 'outlane', 'file': 'Outlane.wav'},
            {'key': 'inlane', 'file': 'Inlane.wav'},
            {'key': 'meltdown', 'file': 'CaptiveBall.ogg'},
            {'key': 'ball_launch', 'file': 'BallLaunchMotorcycle.wav'},
            {'key': 'drop_target', 'file': 'DropTarget.ogg'},
            {'key': 'extra_ball_target', 'file': 'ExtraBallTargetLower.wav'},
            {'key': 'shooterL_launch', 'file': 'LeftKickBack.ogg'},
            {'key': 'outer_loop', 'file': 'BallLaunchMotorcycle.wav'},
            {'key': 'inner_loop', 'file': 'BallLaunchMotorcycle.wav'},
            {'key': 'mystery', 'file': 'Question Mark.wav'},
            {'key': 'right_ramp', 'file': 'RightRampFlyBy.ogg'},
            {'key': 'left_ramp', 'file': 'LoopFlyBy.wav'},
            {'key': 'slingshot', 'file': 'Slingshot.wav'},
            {'key': 'bonus', 'file': 'DropTarget.ogg'}
        ]

        voice_files = [
            {'key': 'attract', 'file': 'attract/jd - dont do drugs.wav'},
            {'key': 'attract', 'file': 'attract/jd - gaze into the fist of dredd.wav'},
            {'key': 'attract', 'file': 'attract/jd - i am the law.wav'},
            {'key': 'attract', 'file': 'judge death/judge death - i have come to bring law to the city my law.wav'},
            {'key': 'attract', 'file': 'judge death/judge death - i have come to bring you the law of death.wav'},
            {'key': 'attract', 'file': 'judge death/judge death - i have come to stop this world again.wav'},
            {'key': 'attract', 'file': 'judge death/judge death - my name is death i have come to judge you.wav'},
            {'key': 'attract', 'file': 'judge death/judge death - the crime is life.wav'},
            {'key': 'attract', 'file': 'judge death/judge death - the sentence is death.wav'},
            {'key': 'attract', 'file': 'judge fire/judge fire - for you the party is over.wav'},
            {'key': 'attract', 'file': 'judge fire/judge fire - let the flames of justice cleanse you.wav'},
            {'key': 'drain', 'file': 'drain/jd - prepare to be judged.wav'},
            {'key': 'boring', 'file': 'boring/jd - its way too quiet.wav'},
            {'key': 'boring', 'file': 'boring/jd - this is boring.wav'},
            {'key': 'boring', 'file': 'boring/wake me when something happens.wav'},
            {'key': 'good shot', 'file': 'good shot/great shot.wav'},
            {'key': 'good shot', 'file': 'good shot/incredible shot.wav'},
            {'key': 'good shot', 'file': 'good shot/jd - do it again.wav'},
            {'key': 'good shot', 'file': 'good shot/jd - excellent.wav'},
            {'key': 'good shot', 'file': 'good shot/wow thats awesome.wav'},
            {'key': 'pursuit intro', 'file': 'pursuit/bank robbery suspects fleeing.wav'},
            {'key': 'pursuit', 'file': 'pursuit/jd - in pursuit 1.wav'},
            {'key': 'pursuit', 'file': 'pursuit/jd - in pursuit 2.wav'},
            {'key': 'pursuit complete', 'file': 'pursuit/jd - suspects apprehended.wav'},
            {'key': 'pursuit failed', 'file': 'pursuit/jd - suspects got away.wav'},
            {'key': 'sniper - miss', 'file': 'sniper/jd - missed him.wav'},
            {'key': 'sniper - miss', 'file': 'sniper/jd - drokk.wav'},
            {'key': 'sniper - miss', 'file': 'sniper/jd - grud.wav'},
            {'key': 'sniper - hit', 'file': 'sniper/jd - sniper neutralized.wav'},
            {'key': 'sniper - hit', 'file': 'sniper/jd - take that punk.wav'},
            {'key': 'sniper - shot', 'file': 'sniper/gunshot.wav'},
            {'key': 'tank intro', 'file': 'battle tank/unknown tank block 1.wav'},
            {'key': 'tank intro', 'file': 'battle tank/unknown tank block 2.wav'},
            {'key': 'tank intro', 'file': 'battle tank/unknown tank block 3.wav'},
            {'key': 'tank intro', 'file': 'battle tank/unknown tank block 4.wav'},
            {'key': 'tank intro', 'file': 'battle tank/unknown tank block 5.wav'},
            {'key': 'tank intro', 'file': 'battle tank/unknown tank block 6.wav'},
            {'key': 'tank intro', 'file': 'battle tank/unknown tank block 7.wav'},
            {'key': 'tank intro', 'file': 'battle tank/unknown tank block 8.wav'},
            {'key': 'tank intro', 'file': 'battle tank/unknown tank block 9.wav'},
            {'key': 'tank intro', 'file': 'battle tank/unknown tank block 10.wav'},
            {'key': 'tank hit 1', 'file': 'battle tank/its damaged but still going.wav'},
            {'key': 'tank hit 2', 'file': 'battle tank/tank hit 1 more shot.wav'},
            {'key': 'tank hit 3', 'file': 'battle tank/tank down.wav'},
            {'key': 'meltdown 1', 'file': 'meltdown/reactor 1 stabilized.wav'},
            {'key': 'meltdown 2', 'file': 'meltdown/reactor 2 stabilized.wav'},
            {'key': 'meltdown 3', 'file': 'meltdown/reactor 3 stabilized.wav'},
            {'key': 'meltdown 4', 'file': 'meltdown/reactor 4 stabilized.wav'},
            {'key': 'meltdown all', 'file': 'meltdown/all reactors stabilized.wav'},
            {'key': 'meltdown intro', 'file': 'meltdown/power towers going critical.wav'},
            {'key': 'bad impersonator ouch', 'file': 'bad impersonator/ouch 1.wav'},
            {'key': 'bad impersonator ouch', 'file': 'bad impersonator/ouch 2.wav'},
            {'key': 'bad impersonator ouch', 'file': 'bad impersonator/ouch 3.wav'},
            {'key': 'bad impersonator ouch', 'file': 'bad impersonator/ouch 4.wav'},
            {'key': 'bad impersonator ouch', 'file': 'bad impersonator/ouch 5.wav'},
            {'key': 'bad impersonator song', 'file': 'bad impersonator/song 1.wav'},
            {'key': 'bad impersonator song', 'file': 'bad impersonator/song 2.wav'},
            {'key': 'bad impersonator song', 'file': 'bad impersonator/song 3.wav'},
            {'key': 'bad impersonator song', 'file': 'bad impersonator/song 4.wav'},
            {'key': 'bad impersonator song', 'file': 'bad impersonator/song 5.wav'},
            {'key': 'bad impersonator boo', 'file': 'bad impersonator/boo 1.wav'},
            {'key': 'bad impersonator boo', 'file': 'bad impersonator/boo 2.wav'},
            {'key': 'bad impersonator boo', 'file': 'bad impersonator/boo 3.wav'},
            {'key': 'bad impersonator boo', 'file': 'bad impersonator/boo 4.wav'},
            {'key': 'bad impersonator boo', 'file': 'bad impersonator/boo 5.wav'},
            {'key': 'bad impersonator shutup', 'file': 'bad impersonator/Shut Up 1.wav'},
            {'key': 'bad impersonator shutup', 'file': 'bad impersonator/Shut Up 2.wav'},
            {'key': 'bad impersonator shutup', 'file': 'bad impersonator/Shut Up 3.wav'},
            {'key': 'bad impersonator shutup', 'file': 'bad impersonator/Shut Up 4.wav'},
            {'key': 'bad impersonator', 'file': 'bad impersonator/bad impersonation in progress.wav'},
            {'key': 'safecracker bad guys', 'file': 'safecracker/hurry up.wav'},
            {'key': 'safecracker bad guys', 'file': 'safecracker/running out of time.wav'},
            {'key': 'safecracker complete', 'file': 'safecracker/jd - youre done.wav'},
            {'key': 'safecracker shot', 'file': 'safecracker/surrounded.wav'},
            {'key': 'safecracker shot', 'file': 'good shot/great shot.wav'},
            {'key': 'safecracker shot', 'file': 'good shot/jd - excellent.wav'},
            {'key': 'safecracker shot', 'file': 'good shot/jd - do it again.wav'},
            {'key': 'manhunt - intro', 'file': 'manhunt/bank robbers trying to escape judgement.wav'},
            {'key': 'manhunt - shot', 'file': 'manhunt/aahh.wav'},
            {'key': 'manhunt - shot', 'file': 'manhunt/jd - i got one.wav'},
            {'key': 'manhunt - shot', 'file': 'manhunt/jd - that will stop him.wav'},
            {'key': 'manhunt - done', 'file': 'manhunt/jd - fugitives captured.wav'},
            {'key': 'stakeout over there', 'file': 'stakeout/jd - over there 1.wav'},
            {'key': 'stakeout over there', 'file': 'stakeout/jd - over there 2.wav'},
            {'key': 'stakeout surrounded', 'file': 'stakeout/jd - we have you surrounded.wav'},
            {'key': 'stakeout move in', 'file': 'stakeout/jd - move in now.wav'},
            {'key': 'stakeout move in', 'file': 'stakeout/jd - thats it take em down.wav'},
            {'key': 'stakeout boring', 'file': 'stakeout/jd - are we sure we have the right place.wav'},
            {'key': 'stakeout boring', 'file': 'stakeout/most boring stakeout ever.wav'},
            {'key': 'stakeout boring', 'file': 'boring/jd - its way too quiet.wav'},
            {'key': 'stakeout boring', 'file': 'boring/jd - this is boring.wav'},
            {'key': 'stakeout boring', 'file': 'boring/wake me when something happens.wav'},
            {'key': 'Block 1 Neutralized', 'file': 'blocks/block 1 neutralized.wav'},
            {'key': 'Block 1 Pacified', 'file': 'blocks/block 1 pacified.wav'},
            {'key': 'Block 1 Secured', 'file': 'blocks/block 1 secured.wav'},
            {'key': 'Block 2 Neutralized', 'file': 'blocks/block 2 neutralized.wav'},
            {'key': 'Block 2 Pacified', 'file': 'blocks/block 2 pacified.wav'},
            {'key': 'Block 2 Secured', 'file': 'blocks/block 2 secured.wav'},
            {'key': 'Block 3 Neutralized', 'file': 'blocks/block 3 neutralized.wav'},
            {'key': 'Block 3 Pacified', 'file': 'blocks/block 3 pacified.wav'},
            {'key': 'Block 3 Secured', 'file': 'blocks/block 3 secured.wav'},
            {'key': 'Block 4 Neutralized', 'file': 'blocks/block 4 neutralized.wav'},
            {'key': 'Block 4 Pacified', 'file': 'blocks/block 4 pacified.wav'},
            {'key': 'Block 4 Secured', 'file': 'blocks/block 4 secured.wav'},
            {'key': 'Block 5 Neutralized', 'file': 'blocks/block 5 neutralized.wav'},
            {'key': 'Block 5 Pacified', 'file': 'blocks/block 5 pacified.wav'},
            {'key': 'Block 5 Secured', 'file': 'blocks/block 5 secured.wav'},
            {'key': 'Block 6 Neutralized', 'file': 'blocks/block 6 neutralized.wav'},
            {'key': 'Block 6 Pacified', 'file': 'blocks/block 6 pacified.wav'},
            {'key': 'Block 6 Secured', 'file': 'blocks/block 6 secured.wav'},
            {'key': 'Block 7 Neutralized', 'file': 'blocks/block 7 neutralized.wav'},
            {'key': 'Block 7 Pacified', 'file': 'blocks/block 7 pacified.wav'},
            {'key': 'Block 7 Secured', 'file': 'blocks/block 7 secured.wav'},
            {'key': 'Block 8 Neutralized', 'file': 'blocks/block 8 neutralized.wav'},
            {'key': 'Block 8 Pacified', 'file': 'blocks/block 8 pacified.wav'},
            {'key': 'Block 8 Secured', 'file': 'blocks/block 8 secured.wav'},
            {'key': 'Block 9 Neutralized', 'file': 'blocks/block 9 neutralized.wav'},
            {'key': 'Block 9 Pacified', 'file': 'blocks/block 9 pacified.wav'},
            {'key': 'Block 9 Secured', 'file': 'blocks/block 9 secured.wav'},
            {'key': 'Block 10 Neutralized', 'file': 'blocks/block 10 neutralized.wav'},
            {'key': 'Block 10 Pacified', 'file': 'blocks/block 10 pacified.wav'},
            {'key': 'Block 10 Secured', 'file': 'blocks/block 10 secured.wav'},
            {'key': 'Block 11 Neutralized', 'file': 'blocks/block 11 neutralized.wav'},
            {'key': 'Block 11 Pacified', 'file': 'blocks/block 11 pacified.wav'},
            {'key': 'Block 11 Secured', 'file': 'blocks/block 11 secured.wav'},
            {'key': 'Block 12 Neutralized', 'file': 'blocks/block 12 neutralized.wav'},
            {'key': 'Block 12 Pacified', 'file': 'blocks/block 12 pacified.wav'},
            {'key': 'Block 12 Secured', 'file': 'blocks/block 12 secured.wav'},
            {'key': 'Block 13 Neutralized', 'file': 'blocks/block 13 neutralized.wav'},
            {'key': 'Block 13 Pacified', 'file': 'blocks/block 13 pacified.wav'},
            {'key': 'Block 13 Secured', 'file': 'blocks/block 13 secured.wav'},
            {'key': 'Block 14 Neutralized', 'file': 'blocks/block 14 neutralized.wav'},
            {'key': 'Block 14 Pacified', 'file': 'blocks/block 14 pacified.wav'},
            {'key': 'Block 14 Secured', 'file': 'blocks/block 14 secured.wav'},
            {'key': 'Block 15 Neutralized', 'file': 'blocks/block 15 neutralized.wav'},
            {'key': 'Block 15 Pacified', 'file': 'blocks/block 15 pacified.wav'},
            {'key': 'Block 15 Secured', 'file': 'blocks/block 15 secured.wav'},
            {'key': 'Block 16 Neutralized', 'file': 'blocks/block 16 neutralized.wav'},
            {'key': 'Block 16 Pacified', 'file': 'blocks/block 16 pacified.wav'},
            {'key': 'Block 16 Secured', 'file': 'blocks/block 16 secured.wav'},
            {'key': 'crime', 'file': 'crimes/crime 1.wav'},
            {'key': 'crime', 'file': 'crimes/crime 2.wav'},
            {'key': 'crime', 'file': 'crimes/crime 3.wav'},
            {'key': 'crime', 'file': 'crimes/crime 4.wav'},
            {'key': 'crime', 'file': 'crimes/crime 5.wav'},
            {'key': 'crime', 'file': 'crimes/crime 6.wav'},
            {'key': 'crime', 'file': 'crimes/crime 7.wav'},
            {'key': 'crime', 'file': 'crimes/crime 8.wav'},
            {'key': 'crime', 'file': 'crimes/crime 9.wav'},
            {'key': 'crime', 'file': 'crimes/crime 10.wav'},
            {'key': 'crime', 'file': 'crimes/crime 11.wav'},
            {'key': 'crime', 'file': 'crimes/crime 12.wav'},
            {'key': 'crime', 'file': 'crimes/crime 13.wav'},
            {'key': 'crime', 'file': 'crimes/crime 14.wav'},
            {'key': 'crime', 'file': 'crimes/crime 15.wav'},
            {'key': 'crime', 'file': 'crimes/crime 16.wav'},
            {'key': 'block war', 'file': 'block war/riot in sector 13.wav'},
            {'key': 'block war', 'file': 'block war/rioting reported.wav'},
            {'key': 'block war', 'file': 'block war/war 1.wav'},
            {'key': 'block war', 'file': 'block war/war 2.wav'},
            {'key': 'block war', 'file': 'block war/war 3.wav'},
            {'key': 'block war', 'file': 'block war/war 4.wav'},
            {'key': 'jackpot is lit', 'file': 'jackpot/jackpot is lit.wav'},
            {'key': 'jackpot', 'file': 'jackpot/jaackpott.wav'},
            {'key': 'jackpot', 'file': 'jackpot/jackpot - excited.wav'},
            {'key': 'shoot the left ramp', 'file': 'multiball/shoot the left ramp.wav'},
            {'key': 'shoot the left ramp', 'file': 'multiball/jd - shoot the left ramp.wav'},
            {'key': 'again', 'file': 'multiball/again.wav'},
            {'key': 'locks lit', 'file': 'multiball/jd - lets lock em up.wav'},
            {'key': 'ball 1 locked', 'file': 'multiball/jd - ball 1 captured.wav'},
            {'key': 'ball 2 locked', 'file': 'multiball/jd - ball 2 locked.wav'},
            {'key': 'multiball', 'file': 'multiball/calling all units the gang has escaped.wav'},
            {'key': 'multiball', 'file': 'multiball/escape from detention block aa23.wav'},
            {'key': 'bad guy shot', 'file': 'shooting gallery/man shot 1.wav'},
            {'key': 'bad guy shot', 'file': 'shooting gallery/man shot 2.wav'},
            {'key': 'bad guy shot', 'file': 'shooting gallery/man shot 3.wav'},
            {'key': 'bad guy shot', 'file': 'shooting gallery/man shot 4.wav'},
            {'key': 'bad guy shot', 'file': 'shooting gallery/man shot 5.wav'},
            {'key': 'good guy shot', 'file': 'shooting gallery/mother 1.wav'},
            {'key': 'good guy shot', 'file': 'shooting gallery/mother 2.wav'},
            {'key': 'moo', 'file': 'shooting gallery/jd - moo.wav'},
            {'key': 'perfect', 'file': 'shooting gallery/perfect.wav'},
            {'key': 'tilt warning', 'file': 'tilt/warning.wav'},
            {'key': 'tilt warning', 'file': 'tilt/jd - im warning you.wav'},
            {'key': 'tilt', 'file': 'tilt/jd - put down your weapons.wav'},
            {'key': 'fire - taunt', 'file': 'judge fire/judge fire - for you the party is over.wav'},
            {'key': 'fire - taunt', 'file': 'judge fire/judge fire - let the flames of justice cleanse you.wav'},
            {'key': 'fear - taunt', 'file': 'judge fear/judge fear - all must die.wav'},
            {'key': 'fear - taunt', 'file': 'judge fear/judge fear - gaze into the face of fear.wav'},
            {'key': 'fear - taunt', 'file': 'judge fear/judge fear - justice must be done.wav'},
            {'key': 'fear - taunt', 'file': 'judge fear/judge fear - there is no escape from justice.wav'},
            {'key': 'mortis - taunt', 'file': 'judge mortis/judge mortis - decay in peace.wav'},
            {'key': 'mortis - taunt', 'file': 'judge mortis/judge mortis - rejoice.wav'},
            {'key': 'mortis - taunt', 'file': 'judge mortis/judge mortis - this city is guilty.wav'},
            {'key': 'mortis - taunt', 'file': 'judge mortis/judge mortis - you cannot hurt us now.wav'},
            {'key': 'death - taunt', 'file': 'judge death/judge death - i have come to bring law to the city my law.wav'},
            {'key': 'death - taunt', 'file': 'judge death/judge death - i have come to bring you the law of death.wav'},
            {'key': 'death - taunt', 'file': 'judge death/judge death - i have come to stop this world again.wav'},
            {'key': 'death - taunt', 'file': 'judge death/judge death - my name is death i have come to judge you.wav'},
            {'key': 'death - taunt', 'file': 'judge death/judge death - the crime is life.wav'},
            {'key': 'death - taunt', 'file': 'judge death/judge death - the sentence is death.wav'},
            {'key': 'death - taunt', 'file': 'judge death/judge death - you cannot kill what does not live.wav'},
            {'key': 'ball saved', 'file': 'ball saved/pity ball.wav'},
            {'key': 'ball saved', 'file': 'ball saved/cant you do better than that.wav'},
            {'key': 'ball saved', 'file': 'ball saved/who told you to stop.wav'},
            {'key': 'ball saved', 'file': 'ball saved/you may judge again.wav'},
            {'key': 'ball saved', 'file': 'ball saved/you may judge again 2.wav'},
            {'key': 'ball saved', 'file': 'ball saved/jd - never do that again.wav'},
            {'key': 'ball saved', 'file': 'ball saved/jd - i can do better than this.wav'},
            {'key': 'curse', 'file': 'curse/jd - curse 1.wav'},
            {'key': 'curse', 'file': 'curse/jd - curse 2.wav'},
            {'key': 'curse', 'file': 'curse/jd - curse 3.wav'},
            {'key': 'curse', 'file': 'curse/jd - curse 4.wav'},
            {'key': 'curse', 'file': 'curse/jd - curse 5.wav'},
            {'key': 'curse', 'file': 'curse/jd - curse 6.wav'},
            {'key': 'curse', 'file': 'curse/jd - curse 7.wav'},
            {'key': 'curse', 'file': 'curse/jd - curse 8.wav'},
            {'key': 'curse', 'file': 'curse/jd - curse 9.wav'},
            {'key': 'curse', 'file': 'curse/jd - curse 10.wav'},
            {'key': 'curse', 'file': 'curse/jd - curse 11.wav'},
            {'key': 'welcome', 'file': 'welcome/welcome.wav'},
            {'key': 'welcome', 'file': 'welcome/jd - reporting for duty.wav'},
            {'key': 'welcome', 'file': 'judge death/judge death - i have come to bring law to the city my law.wav'},
            {'key': 'welcome', 'file': 'judge death/judge death - i have come to stop this world again.wav'},
            {'key': 'shoot again 1', 'file': 'shoot again/shoot again player 1.wav'},
            {'key': 'shoot again 2', 'file': 'shoot again/shoot again player 2.wav'},
            {'key': 'shoot again 3', 'file': 'shoot again/shoot again player 3.wav'},
            {'key': 'shoot again 4', 'file': 'shoot again/shoot again player 4.wav'},
            {'key': 'high score', 'file': 'high score/congratulations.wav'}
        ]

        fonts_files = [
            {'key': 'tiny', 'file': '04B-03-7px.dmd'},
            {'key': 'medium', 'file': 'Font07x5.dmd'},
            {'key': 'large_num', 'file': 'Font14x10.dmd'},
            {'key': 'large', 'file': 'Jazz18-18px.dmd'},
        ]

        assets_path = curr_file_path + '/assets'

        animations_prefix = assets_path + '/dmd/'
        for asset in animations_files:
            anim = Animation().load(animations_prefix + asset['file'])
            repeat = asset.get('repeat', False)
            hold_last_frame = asset.get('holdLastFrame', False)
            frame_time = asset.get('frame_time', 1)
            layer = AnimatedLayer(frames=anim.frames, repeat=repeat, hold=hold_last_frame, frame_time=frame_time)
            composite_op = asset.get('composite_op')
            if composite_op:
                layer.composite_op = composite_op
            self.animations[asset['key']] = layer

        lampshow_prefix = assets_path + '/lamps/'
        for asset in lampshow_files:
            self.game.lampctrl.register_show(asset['key'], lampshow_prefix + asset['file'])

        music_prefix = assets_path + '/sound/music/'
        for asset in music_files:
            self.game.sound.register_music(asset['key'], music_prefix + asset['file'])

        effects_prefix = assets_path + '/sound/sfx/'
        for asset in effects_files:
            self.game.sound.register_sound(asset['key'], effects_prefix + asset['file'])

        voice_prefix = assets_path + '/sound/voice/'
        for asset in voice_files:
            self.game.sound.register_sound(asset['key'], voice_prefix + asset['file'])

        for asset in fonts_files:
            self.fonts[asset['key']] = font_named(asset['file'])
