#!/bin/sh
# This script copies the JD-pyprocgame media kit
# creating a directory structure suitable for JD2-pyprocgame

media=jd_media_02

cp $media/LICENSE.media assets/LICENSE.media

mkdir "assets/dmd"
mkdir "assets/dmd/unused"
cp "$media/dmd/bikeacrosscity.dmd" "assets/dmd/bikeacrosscity.dmd"
cp "$media/dmd/bike_across_screen.dmd" "assets/dmd/bike_across_screen.dmd"
cp "$media/dmd/blackout.dmd" "assets/dmd/blackout.dmd"
cp "$media/dmd/blockwars.dmd" "assets/dmd/blockwars.dmd"
cp "$media/dmd/cityscape.dmd" "assets/dmd/cityscape.dmd"
cp "$media/dmd/cows.dmd" "assets/dmd/cows.dmd"
cp "$media/dmd/darkjudges.dmd" "assets/dmd/darkjudges.dmd"
cp "$media/dmd/dredd_shoot_at_sniper.dmd" "assets/dmd/dredd_shoot_at_sniper.dmd"
cp "$media/dmd/EBAnim.dmd" "assets/dmd/extra_ball.dmd"
cp "$media/dmd/gun_powerup.dmd" "assets/dmd/gun_powerup.dmd"
cp "$media/dmd/jdpeople.dmd" "assets/dmd/jdpeople.dmd"
cp "$media/dmd/longwalk.dmd" "assets/dmd/longwalk.dmd"
cp "$media/dmd/scopeandshot.dmd" "assets/dmd/scopeandshot.dmd"
cp "$media/dmd/bullets.dmd" "assets/dmd/unused/bullets.dmd"
cp "$media/dmd/busted.dmd" "assets/dmd/unused/busted.dmd"
cp "$media/dmd/carbank.dmd" "assets/dmd/unused/carbank.dmd"
cp "$media/dmd/deadworld.dmd" "assets/dmd/unused/deadworld.dmd"
cp "$media/dmd/fire1.dmd" "assets/dmd/unused/fire1.dmd"
cp "$media/dmd/guntech.dmd" "assets/dmd/unused/guntech.dmd"
cp "$media/dmd/judgesincrystals.dmd" "assets/dmd/unused/judgesincrystals.dmd"
cp "$media/dmd/scope.dmd" "assets/dmd/unused/scope.dmd"
cp "$media/dmd/subway.dmd" "assets/dmd/unused/subway.dmd"
cp "$media/dmd/train1.dmd" "assets/dmd/unused/train1.dmd"

mkdir "assets/sound"
mkdir "assets/sound/effects"
cp "$media/sound/FX/BallLaunchMotorcycle.wav" "assets/sound/effects/BallLaunchMotorcycle.wav"
cp "$media/sound/FX/CaptiveBall.ogg" "assets/sound/effects/CaptiveBall.ogg"
cp "$media/sound/FX/DropTarget.ogg" "assets/sound/effects/DropTarget.ogg"
cp "$media/sound/FX/ExtraBallTargetLower.wav" "assets/sound/effects/ExtraBallTargetLower.wav"
cp "$media/sound/FX/Inlane.wav" "assets/sound/effects/Inlane.wav"
cp "$media/sound/FX/left kickback.ogg" "assets/sound/effects/LeftKickBack.ogg"
cp "$media/sound/FX/LoopFlyBy.wav" "assets/sound/effects/LoopFlyBy.wav"
cp "$media/sound/FX/Outlane.wav" "assets/sound/effects/Outlane.wav"
cp "$media/sound/FX/Question Mark.wav" "assets/sound/effects/Question Mark.wav"
cp "$media/sound/FX/RightRampFlyBy.ogg" "assets/sound/effects/RightRampFlyBy.ogg"
cp "$media/sound/FX/Slingshot.wav" "assets/sound/effects/Slingshot.wav"

mkdir "assets/sound"
mkdir "assets/sound/music"
cp "$media/sound/105 second loopable -- Sisyphus.aif" "assets/sound/music/105 second loopable -- Sisyphus.aif"
cp "$media/sound/40 Second guitar solo.aif" "assets/sound/music/40 Second guitar solo.aif"
cp "$media/sound/55 second loopable -- Sonya.aif" "assets/sound/music/55 second loopable -- Sonya.aif"
cp "$media/sound/brainsDarkMelody(161).aif" "assets/sound/music/brainsDarkMelody(161).aif"
cp "$media/sound/Heroes and Angels -- Loopable.aif" "assets/sound/music/Heroes and Angels -- Loopable.aif"
cp "$media/sound/introloop(161).aif" "assets/sound/music/introloop(161).aif"

mkdir "assets/sound/voice"
mkdir "assets/sound/voice/attract"
mkdir "assets/sound/voice/bad impersonator"
mkdir "assets/sound/voice/ball saved"
mkdir "assets/sound/voice/battle tank"
mkdir "assets/sound/voice/block war"
mkdir "assets/sound/voice/blocks"
mkdir "assets/sound/voice/boring"
mkdir "assets/sound/voice/crimes"
mkdir "assets/sound/voice/curse"
mkdir "assets/sound/voice/drain"
mkdir "assets/sound/voice/good shot"
mkdir "assets/sound/voice/high score"
mkdir "assets/sound/voice/jackpot"
mkdir "assets/sound/voice/judge death"
mkdir "assets/sound/voice/judge fear"
mkdir "assets/sound/voice/judge fire"
mkdir "assets/sound/voice/judge mortis"
mkdir "assets/sound/voice/manhunt"
mkdir "assets/sound/voice/meltdown"
mkdir "assets/sound/voice/multiball"
mkdir "assets/sound/voice/pursuit"
mkdir "assets/sound/voice/safecracker"
mkdir "assets/sound/voice/shoot again"
mkdir "assets/sound/voice/shooting gallery"
mkdir "assets/sound/voice/skillshot"
mkdir "assets/sound/voice/sniper"
mkdir "assets/sound/voice/stakeout"
mkdir "assets/sound/voice/tilt"
mkdir "assets/sound/voice/unused"
mkdir "assets/sound/voice/welcome"

cp "$media/sound/Voice/attract/jd - dont do drugs.wav" "assets/sound/voice/attract/jd - dont do drugs.wav"
cp "$media/sound/Voice/attract/jd - gaze into the fist of dredd.wav" "assets/sound/voice/attract/jd - gaze into the fist of dredd.wav"
cp "$media/sound/Voice/attract/jd - i am the law.wav" "assets/sound/voice/attract/jd - i am the law.wav"
cp "$media/sound/Voice/bad_impersonator/bad impersonation in progress.wav" "assets/sound/voice/bad impersonator/bad impersonation in progress.wav"
cp "$media/sound/Voice/bad_impersonator/boo 1.wav" "assets/sound/voice/bad impersonator/boo 1.wav"
cp "$media/sound/Voice/bad_impersonator/boo 2.wav" "assets/sound/voice/bad impersonator/boo 2.wav"
cp "$media/sound/Voice/bad_impersonator/boo 3.wav" "assets/sound/voice/bad impersonator/boo 3.wav"
cp "$media/sound/Voice/bad_impersonator/boo 4.wav" "assets/sound/voice/bad impersonator/boo 4.wav"
cp "$media/sound/Voice/bad_impersonator/boo 5.wav" "assets/sound/voice/bad impersonator/boo 5.wav"
cp "$media/sound/Voice/bad_impersonator/ouch 1.wav" "assets/sound/voice/bad impersonator/ouch 1.wav"
cp "$media/sound/Voice/bad_impersonator/ouch 2.wav" "assets/sound/voice/bad impersonator/ouch 2.wav"
cp "$media/sound/Voice/bad_impersonator/ouch 3.wav" "assets/sound/voice/bad impersonator/ouch 3.wav"
cp "$media/sound/Voice/bad_impersonator/ouch 4.wav" "assets/sound/voice/bad impersonator/ouch 4.wav"
cp "$media/sound/Voice/bad_impersonator/ouch 5.wav" "assets/sound/voice/bad impersonator/ouch 5.wav"
cp "$media/sound/Voice/bad_impersonator/Shut Up 1.wav" "assets/sound/voice/bad impersonator/Shut Up 1.wav"
cp "$media/sound/Voice/bad_impersonator/Shut Up 2.wav" "assets/sound/voice/bad impersonator/Shut Up 2.wav"
cp "$media/sound/Voice/bad_impersonator/Shut Up 3.wav" "assets/sound/voice/bad impersonator/Shut Up 3.wav"
cp "$media/sound/Voice/bad_impersonator/Shut Up 4.wav" "assets/sound/voice/bad impersonator/Shut Up 4.wav"
cp "$media/sound/Voice/bad_impersonator/song 1.wav" "assets/sound/voice/bad impersonator/song 1.wav"
cp "$media/sound/Voice/bad_impersonator/song 2.wav" "assets/sound/voice/bad impersonator/song 2.wav"
cp "$media/sound/Voice/bad_impersonator/song 3.wav" "assets/sound/voice/bad impersonator/song 3.wav"
cp "$media/sound/Voice/bad_impersonator/song 4.wav" "assets/sound/voice/bad impersonator/song 4.wav"
cp "$media/sound/Voice/bad_impersonator/song 5.wav" "assets/sound/voice/bad impersonator/song 5.wav"
cp "$media/sound/Voice/cant you do better than that.wav" "assets/sound/voice/ball saved/cant you do better than that.wav"
cp "$media/sound/Voice/jd - i can do better than this.wav" "assets/sound/voice/ball saved/jd - i can do better than this.wav"
cp "$media/sound/Voice/jd - never do that again.wav" "assets/sound/voice/ball saved/jd - never do that again.wav"
cp "$media/sound/Voice/pity ball.wav" "assets/sound/voice/ball saved/pity ball.wav"
cp "$media/sound/Voice/who told you to stop.wav" "assets/sound/voice/ball saved/who told you to stop.wav"
cp "$media/sound/Voice/you may judge again 2.wav" "assets/sound/voice/ball saved/you may judge again 2.wav"
cp "$media/sound/Voice/you may judge again.wav" "assets/sound/voice/ball saved/you may judge again.wav"
cp "$media/sound/Voice/battle_tank/its damaged but still going.wav" "assets/sound/voice/battle tank/its damaged but still going.wav"
cp "$media/sound/Voice/battle_tank/tank down.wav" "assets/sound/voice/battle tank/tank down.wav"
cp "$media/sound/Voice/battle_tank/tank hit 1 more shot.wav" "assets/sound/voice/battle tank/tank hit 1 more shot.wav"
cp "$media/sound/Voice/battle_tank/unknown tank block 1.wav" "assets/sound/voice/battle tank/unknown tank block 1.wav"
cp "$media/sound/Voice/battle_tank/unknown tank block 10.wav" "assets/sound/voice/battle tank/unknown tank block 10.wav"
cp "$media/sound/Voice/battle_tank/unknown tank block 2.wav" "assets/sound/voice/battle tank/unknown tank block 2.wav"
cp "$media/sound/Voice/battle_tank/unknown tank block 3.wav" "assets/sound/voice/battle tank/unknown tank block 3.wav"
cp "$media/sound/Voice/battle_tank/unknown tank block 4.wav" "assets/sound/voice/battle tank/unknown tank block 4.wav"
cp "$media/sound/Voice/battle_tank/unknown tank block 5.wav" "assets/sound/voice/battle tank/unknown tank block 5.wav"
cp "$media/sound/Voice/battle_tank/unknown tank block 6.wav" "assets/sound/voice/battle tank/unknown tank block 6.wav"
cp "$media/sound/Voice/battle_tank/unknown tank block 7.wav" "assets/sound/voice/battle tank/unknown tank block 7.wav"
cp "$media/sound/Voice/battle_tank/unknown tank block 8.wav" "assets/sound/voice/battle tank/unknown tank block 8.wav"
cp "$media/sound/Voice/battle_tank/unknown tank block 9.wav" "assets/sound/voice/battle tank/unknown tank block 9.wav"
cp "$media/sound/Voice/crimescenes/riot in sector 13.wav" "assets/sound/voice/block war/riot in sector 13.wav"
cp "$media/sound/Voice/crimescenes/rioting reported.wav" "assets/sound/voice/block war/rioting reported.wav"
cp "$media/sound/Voice/crimescenes/war 1.wav" "assets/sound/voice/block war/war 1.wav"
cp "$media/sound/Voice/crimescenes/war 2.wav" "assets/sound/voice/block war/war 2.wav"
cp "$media/sound/Voice/crimescenes/war 3.wav" "assets/sound/voice/block war/war 3.wav"
cp "$media/sound/Voice/crimescenes/war 4.wav" "assets/sound/voice/block war/war 4.wav"
cp "$media/sound/Voice/crimescenes/block 1 neutralized.wav" "assets/sound/voice/blocks/block 1 neutralized.wav"
cp "$media/sound/Voice/crimescenes/block 1 pacified.wav" "assets/sound/voice/blocks/block 1 pacified.wav"
cp "$media/sound/Voice/crimescenes/block 1 secured.wav" "assets/sound/voice/blocks/block 1 secured.wav"
cp "$media/sound/Voice/crimescenes/block 10 neutralized.wav" "assets/sound/voice/blocks/block 10 neutralized.wav"
cp "$media/sound/Voice/crimescenes/block 10 pacified.wav" "assets/sound/voice/blocks/block 10 pacified.wav"
cp "$media/sound/Voice/crimescenes/block 10 secured.wav" "assets/sound/voice/blocks/block 10 secured.wav"
cp "$media/sound/Voice/crimescenes/block 11 neutralized.wav" "assets/sound/voice/blocks/block 11 neutralized.wav"
cp "$media/sound/Voice/crimescenes/block 11 pacified.wav" "assets/sound/voice/blocks/block 11 pacified.wav"
cp "$media/sound/Voice/crimescenes/block 11 secured.wav" "assets/sound/voice/blocks/block 11 secured.wav"
cp "$media/sound/Voice/crimescenes/block 12 neutralized.wav" "assets/sound/voice/blocks/block 12 neutralized.wav"
cp "$media/sound/Voice/crimescenes/block 12 pacified.wav" "assets/sound/voice/blocks/block 12 pacified.wav"
cp "$media/sound/Voice/crimescenes/block 12 secured.wav" "assets/sound/voice/blocks/block 12 secured.wav"
cp "$media/sound/Voice/crimescenes/block 13 neutralized.wav" "assets/sound/voice/blocks/block 13 neutralized.wav"
cp "$media/sound/Voice/crimescenes/block 13 pacified.wav" "assets/sound/voice/blocks/block 13 pacified.wav"
cp "$media/sound/Voice/crimescenes/block 13 secured.wav" "assets/sound/voice/blocks/block 13 secured.wav"
cp "$media/sound/Voice/crimescenes/block 14 neutralized.wav" "assets/sound/voice/blocks/block 14 neutralized.wav"
cp "$media/sound/Voice/crimescenes/block 14 pacified.wav" "assets/sound/voice/blocks/block 14 pacified.wav"
cp "$media/sound/Voice/crimescenes/block 14 secured.wav" "assets/sound/voice/blocks/block 14 secured.wav"
cp "$media/sound/Voice/crimescenes/block 15 neutralized.wav" "assets/sound/voice/blocks/block 15 neutralized.wav"
cp "$media/sound/Voice/crimescenes/block 15 pacified.wav" "assets/sound/voice/blocks/block 15 pacified.wav"
cp "$media/sound/Voice/crimescenes/block 15 secured.wav" "assets/sound/voice/blocks/block 15 secured.wav"
cp "$media/sound/Voice/crimescenes/block 16 neutralized.wav" "assets/sound/voice/blocks/block 16 neutralized.wav"
cp "$media/sound/Voice/crimescenes/block 16 pacified.wav" "assets/sound/voice/blocks/block 16 pacified.wav"
cp "$media/sound/Voice/crimescenes/block 16 secured.wav" "assets/sound/voice/blocks/block 16 secured.wav"
cp "$media/sound/Voice/crimescenes/block 2 neutralized.wav" "assets/sound/voice/blocks/block 2 neutralized.wav"
cp "$media/sound/Voice/crimescenes/block 2 pacified.wav" "assets/sound/voice/blocks/block 2 pacified.wav"
cp "$media/sound/Voice/crimescenes/block 2 secured.wav" "assets/sound/voice/blocks/block 2 secured.wav"
cp "$media/sound/Voice/crimescenes/block 3 neutralized.wav" "assets/sound/voice/blocks/block 3 neutralized.wav"
cp "$media/sound/Voice/crimescenes/block 3 pacified.wav" "assets/sound/voice/blocks/block 3 pacified.wav"
cp "$media/sound/Voice/crimescenes/block 3 secured.wav" "assets/sound/voice/blocks/block 3 secured.wav"
cp "$media/sound/Voice/crimescenes/block 4 neutralized.wav" "assets/sound/voice/blocks/block 4 neutralized.wav"
cp "$media/sound/Voice/crimescenes/block 4 pacified.wav" "assets/sound/voice/blocks/block 4 pacified.wav"
cp "$media/sound/Voice/crimescenes/block 4 secured.wav" "assets/sound/voice/blocks/block 4 secured.wav"
cp "$media/sound/Voice/crimescenes/block 5 neutralized.wav" "assets/sound/voice/blocks/block 5 neutralized.wav"
cp "$media/sound/Voice/crimescenes/block 5 pacified.wav" "assets/sound/voice/blocks/block 5 pacified.wav"
cp "$media/sound/Voice/crimescenes/block 5 secured.wav" "assets/sound/voice/blocks/block 5 secured.wav"
cp "$media/sound/Voice/crimescenes/block 6 neutralized.wav" "assets/sound/voice/blocks/block 6 neutralized.wav"
cp "$media/sound/Voice/crimescenes/block 6 pacified.wav" "assets/sound/voice/blocks/block 6 pacified.wav"
cp "$media/sound/Voice/crimescenes/block 6 secured.wav" "assets/sound/voice/blocks/block 6 secured.wav"
cp "$media/sound/Voice/crimescenes/block 7 neutralized.wav" "assets/sound/voice/blocks/block 7 neutralized.wav"
cp "$media/sound/Voice/crimescenes/block 7 pacified.wav" "assets/sound/voice/blocks/block 7 pacified.wav"
cp "$media/sound/Voice/crimescenes/block 7 secured.wav" "assets/sound/voice/blocks/block 7 secured.wav"
cp "$media/sound/Voice/crimescenes/block 8 neutralized.wav" "assets/sound/voice/blocks/block 8 neutralized.wav"
cp "$media/sound/Voice/crimescenes/block 8 pacified.wav" "assets/sound/voice/blocks/block 8 pacified.wav"
cp "$media/sound/Voice/crimescenes/block 8 secured.wav" "assets/sound/voice/blocks/block 8 secured.wav"
cp "$media/sound/Voice/crimescenes/block 9 neutralized.wav" "assets/sound/voice/blocks/block 9 neutralized.wav"
cp "$media/sound/Voice/crimescenes/block 9 pacified.wav" "assets/sound/voice/blocks/block 9 pacified.wav"
cp "$media/sound/Voice/crimescenes/block 9 secured.wav" "assets/sound/voice/blocks/block 9 secured.wav"
cp "$media/sound/Voice/boring/jd - its way too quiet.wav" "assets/sound/voice/boring/jd - its way too quiet.wav"
cp "$media/sound/Voice/boring/jd - this is boring.wav" "assets/sound/voice/boring/jd - this is boring.wav"
cp "$media/sound/Voice/boring/wake me when something happens.wav" "assets/sound/voice/boring/wake me when something happens.wav"
cp "$media/sound/Voice/crimescenes/crime 1.wav" "assets/sound/voice/crimes/crime 1.wav"
cp "$media/sound/Voice/crimescenes/crime 10.wav" "assets/sound/voice/crimes/crime 10.wav"
cp "$media/sound/Voice/crimescenes/crime 11.wav" "assets/sound/voice/crimes/crime 11.wav"
cp "$media/sound/Voice/crimescenes/crime 12.wav" "assets/sound/voice/crimes/crime 12.wav"
cp "$media/sound/Voice/crimescenes/crime 13.wav" "assets/sound/voice/crimes/crime 13.wav"
cp "$media/sound/Voice/crimescenes/crime 14.wav" "assets/sound/voice/crimes/crime 14.wav"
cp "$media/sound/Voice/crimescenes/crime 15.wav" "assets/sound/voice/crimes/crime 15.wav"
cp "$media/sound/Voice/crimescenes/crime 16.wav" "assets/sound/voice/crimes/crime 16.wav"
cp "$media/sound/Voice/crimescenes/crime 2.wav" "assets/sound/voice/crimes/crime 2.wav"
cp "$media/sound/Voice/crimescenes/crime 3.wav" "assets/sound/voice/crimes/crime 3.wav"
cp "$media/sound/Voice/crimescenes/crime 4.wav" "assets/sound/voice/crimes/crime 4.wav"
cp "$media/sound/Voice/crimescenes/crime 5.wav" "assets/sound/voice/crimes/crime 5.wav"
cp "$media/sound/Voice/crimescenes/crime 6.wav" "assets/sound/voice/crimes/crime 6.wav"
cp "$media/sound/Voice/crimescenes/crime 7.wav" "assets/sound/voice/crimes/crime 7.wav"
cp "$media/sound/Voice/crimescenes/crime 8.wav" "assets/sound/voice/crimes/crime 8.wav"
cp "$media/sound/Voice/crimescenes/crime 9.wav" "assets/sound/voice/crimes/crime 9.wav"
cp "$media/sound/Voice/jd - curse 1.wav" "assets/sound/voice/curse/jd - curse 1.wav"
cp "$media/sound/Voice/jd - curse 10.wav" "assets/sound/voice/curse/jd - curse 10.wav"
cp "$media/sound/Voice/jd - curse 11.wav" "assets/sound/voice/curse/jd - curse 11.wav"
cp "$media/sound/Voice/jd - curse 2.wav" "assets/sound/voice/curse/jd - curse 2.wav"
cp "$media/sound/Voice/jd - curse 3.wav" "assets/sound/voice/curse/jd - curse 3.wav"
cp "$media/sound/Voice/jd - curse 4.wav" "assets/sound/voice/curse/jd - curse 4.wav"
cp "$media/sound/Voice/jd - curse 5.wav" "assets/sound/voice/curse/jd - curse 5.wav"
cp "$media/sound/Voice/jd - curse 6.wav" "assets/sound/voice/curse/jd - curse 6.wav"
cp "$media/sound/Voice/jd - curse 7.wav" "assets/sound/voice/curse/jd - curse 7.wav"
cp "$media/sound/Voice/jd - curse 8.wav" "assets/sound/voice/curse/jd - curse 8.wav"
cp "$media/sound/Voice/jd - curse 9.wav" "assets/sound/voice/curse/jd - curse 9.wav"
cp "$media/sound/Voice/drain/jd - prepare to be judged.wav" "assets/sound/voice/drain/jd - prepare to be judged.wav"
cp "$media/sound/Voice/skillshot/great shot.wav" "assets/sound/voice/good shot/great shot.wav"
cp "$media/sound/Voice/skillshot/incredible shot.wav" "assets/sound/voice/good shot/incredible shot.wav"
cp "$media/sound/Voice/skillshot/jd - do it again.wav" "assets/sound/voice/good shot/jd - do it again.wav"
cp "$media/sound/Voice/skillshot/jd - excellent.wav" "assets/sound/voice/good shot/jd - excellent.wav"
cp "$media/sound/Voice/skillshot/wow thats awesome.wav" "assets/sound/voice/good shot/wow thats awesome.wav"
cp "$media/sound/Voice/congratulations.wav" "assets/sound/voice/high score/congratulations.wav"
cp "$media/sound/Voice/multiball/jaackpott.wav" "assets/sound/voice/jackpot/jaackpott.wav"
cp "$media/sound/Voice/multiball/jackpot - excited.wav" "assets/sound/voice/jackpot/jackpot - excited.wav"
cp "$media/sound/Voice/multiball/jackpot is lit.wav" "assets/sound/voice/jackpot/jackpot is lit.wav"
cp "$media/sound/Voice/ultimate_challenge/judge death - i have come to bring law to the city my law.wav" "assets/sound/voice/judge death/judge death - i have come to bring law to the city my law.wav"
cp "$media/sound/Voice/attract/judge death - i have come to bring you the law of death.wav" "assets/sound/voice/judge death/judge death - i have come to bring you the law of death.wav"
cp "$media/sound/Voice/ultimate_challenge/judge death - i have come to stop this world again.wav" "assets/sound/voice/judge death/judge death - i have come to stop this world again.wav"
cp "$media/sound/Voice/ultimate_challenge/judge death - my name is death i have come to judge you.wav" "assets/sound/voice/judge death/judge death - my name is death i have come to judge you.wav"
cp "$media/sound/Voice/ultimate_challenge/judge death - the crime is life.wav" "assets/sound/voice/judge death/judge death - the crime is life.wav"
cp "$media/sound/Voice/ultimate_challenge/judge death - the sentence is death.wav" "assets/sound/voice/judge death/judge death - the sentence is death.wav"
cp "$media/sound/Voice/ultimate_challenge/judge death - you cannot kill what does not live.wav" "assets/sound/voice/judge death/judge death - you cannot kill what does not live.wav"
cp "$media/sound/Voice/ultimate_challenge/judge fear - all must die.wav" "assets/sound/voice/judge fear/judge fear - all must die.wav"
cp "$media/sound/Voice/ultimate_challenge/judge fear - gaze into the face of fear.wav" "assets/sound/voice/judge fear/judge fear - gaze into the face of fear.wav"
cp "$media/sound/Voice/ultimate_challenge/judge fear - justice must be done.wav" "assets/sound/voice/judge fear/judge fear - justice must be done.wav"
cp "$media/sound/Voice/ultimate_challenge/judge fear - there is no escape from justice.wav" "assets/sound/voice/judge fear/judge fear - there is no escape from justice.wav"
cp "$media/sound/Voice/ultimate_challenge/judge fire - for you the party is over.wav" "assets/sound/voice/judge fire/judge fire - for you the party is over.wav"
cp "$media/sound/Voice/ultimate_challenge/judge fire - let the flames of justice cleanse you.wav" "assets/sound/voice/judge fire/judge fire - let the flames of justice cleanse you.wav"
cp "$media/sound/Voice/ultimate_challenge/judge mortis - decay in peace.wav" "assets/sound/voice/judge mortis/judge mortis - decay in peace.wav"
cp "$media/sound/Voice/ultimate_challenge/judge mortis - rejoice.wav" "assets/sound/voice/judge mortis/judge mortis - rejoice.wav"
cp "$media/sound/Voice/ultimate_challenge/judge mortis - this city is guilty.wav" "assets/sound/voice/judge mortis/judge mortis - this city is guilty.wav"
cp "$media/sound/Voice/ultimate_challenge/judge mortis - you cannot hurt us now.wav" "assets/sound/voice/judge mortis/judge mortis - you cannot hurt us now.wav"
cp "$media/sound/Voice/manhunt/aahh.wav" "assets/sound/voice/manhunt/aahh.wav"
cp "$media/sound/Voice/manhunt/bank robbers trying to escape judgement.wav" "assets/sound/voice/manhunt/bank robbers trying to escape judgement.wav"
cp "$media/sound/Voice/manhunt/jd - fugutives captured.wav" "assets/sound/voice/manhunt/jd - fugitives captured.wav"
cp "$media/sound/Voice/manhunt/jd - i got one.wav" "assets/sound/voice/manhunt/jd - i got one.wav"
cp "$media/sound/Voice/manhunt/jd - that will stop him.wav" "assets/sound/voice/manhunt/jd - that will stop him.wav"
cp "$media/sound/Voice/meltdown/all reactors stabilized.wav" "assets/sound/voice/meltdown/all reactors stabilized.wav"
cp "$media/sound/Voice/meltdown/power towers going critical.wav" "assets/sound/voice/meltdown/power towers going critical.wav"
cp "$media/sound/Voice/meltdown/reactor 1 stabilized.wav" "assets/sound/voice/meltdown/reactor 1 stabilized.wav"
cp "$media/sound/Voice/meltdown/reactor 2 stabilized.wav" "assets/sound/voice/meltdown/reactor 2 stabilized.wav"
cp "$media/sound/Voice/meltdown/reactor 3 stabilized.wav" "assets/sound/voice/meltdown/reactor 3 stabilized.wav"
cp "$media/sound/Voice/meltdown/reactor 4 stabilized.wav" "assets/sound/voice/meltdown/reactor 4 stabilized.wav"
cp "$media/sound/Voice/multiball/again.wav" "assets/sound/voice/multiball/again.wav"
cp "$media/sound/Voice/multiball/calling all units the gang has escaped.wav" "assets/sound/voice/multiball/calling all units the gang has escaped.wav"
cp "$media/sound/Voice/multiball/escape from detention block aa23.wav" "assets/sound/voice/multiball/escape from detention block aa23.wav"
cp "$media/sound/Voice/multiball/jd - ball 1 captured.wav" "assets/sound/voice/multiball/jd - ball 1 captured.wav"
cp "$media/sound/Voice/multiball/jd - ball 2 locked.wav" "assets/sound/voice/multiball/jd - ball 2 locked.wav"
cp "$media/sound/Voice/multiball/jd - lets lock em up.wav" "assets/sound/voice/multiball/jd - lets lock em up.wav"
cp "$media/sound/Voice/multiball/jd - shoot the left ramp.wav" "assets/sound/voice/multiball/jd - shoot the left ramp.wav"
cp "$media/sound/Voice/multiball/shoot the left ramp.wav" "assets/sound/voice/multiball/shoot the left ramp.wav"
cp "$media/sound/Voice/pursuit/bank robbery suspects fleeing.wav" "assets/sound/voice/pursuit/bank robbery suspects fleeing.wav"
cp "$media/sound/Voice/pursuit/jd - in pursuit 1.wav" "assets/sound/voice/pursuit/jd - in pursuit 1.wav"
cp "$media/sound/Voice/pursuit/jd - in pursuit 2.wav" "assets/sound/voice/pursuit/jd - in pursuit 2.wav"
cp "$media/sound/Voice/pursuit/suspects apprehended.wav" "assets/sound/voice/pursuit/jd - suspects apprehended.wav"
cp "$media/sound/Voice/pursuit/suspects got away.wav" "assets/sound/voice/pursuit/jd - suspects got away.wav"
cp "$media/sound/Voice/safecracker/hurry up.wav" "assets/sound/voice/safecracker/hurry up.wav"
cp "$media/sound/Voice/safecracker/jd - youre done.wav" "assets/sound/voice/safecracker/jd - youre done.wav"
cp "$media/sound/Voice/safecracker/running out of time.wav" "assets/sound/voice/safecracker/running out of time.wav"
cp "$media/sound/Voice/safecracker/surrounded.wav" "assets/sound/voice/safecracker/surrounded.wav"
cp "$media/sound/Voice/shoot again player 1.wav" "assets/sound/voice/shoot again/shoot again player 1.wav"
cp "$media/sound/Voice/shoot again player 2.wav" "assets/sound/voice/shoot again/shoot again player 2.wav"
cp "$media/sound/Voice/shoot again player 3.wav" "assets/sound/voice/shoot again/shoot again player 3.wav"
cp "$media/sound/Voice/shoot again player 4.wav" "assets/sound/voice/shoot again/shoot again player 4.wav"
cp "$media/sound/Voice/jd - moo.wav" "assets/sound/voice/shooting gallery/jd - moo.wav"
cp "$media/sound/Voice/shooting_gallery/man shot 1.wav" "assets/sound/voice/shooting gallery/man shot 1.wav"
cp "$media/sound/Voice/shooting_gallery/man shot 2.wav" "assets/sound/voice/shooting gallery/man shot 2.wav"
cp "$media/sound/Voice/shooting_gallery/man shot 3.wav" "assets/sound/voice/shooting gallery/man shot 3.wav"
cp "$media/sound/Voice/shooting_gallery/man shot 4.wav" "assets/sound/voice/shooting gallery/man shot 4.wav"
cp "$media/sound/Voice/shooting_gallery/man shot 5.wav" "assets/sound/voice/shooting gallery/man shot 5.wav"
cp "$media/sound/Voice/shooting_gallery/mother 1.wav" "assets/sound/voice/shooting gallery/mother 1.wav"
cp "$media/sound/Voice/shooting_gallery/mother 2.wav" "assets/sound/voice/shooting gallery/mother 2.wav"
cp "$media/sound/Voice/unused/perfect.wav" "assets/sound/voice/shooting gallery/perfect.wav"
cp "$media/sound/Voice/sniper/gunshot.wav" "assets/sound/voice/sniper/gunshot.wav"
cp "$media/sound/Voice/sniper/jd - drokk.wav" "assets/sound/voice/sniper/jd - drokk.wav"
cp "$media/sound/Voice/sniper/jd - grud.wav" "assets/sound/voice/sniper/jd - grud.wav"
cp "$media/sound/Voice/sniper/jd - missed him.wav" "assets/sound/voice/sniper/jd - missed him.wav"
cp "$media/sound/Voice/sniper/jd - sniper neutralized.wav" "assets/sound/voice/sniper/jd - sniper neutralized.wav"
cp "$media/sound/Voice/sniper/jd - take that punk.wav" "assets/sound/voice/sniper/jd - take that punk.wav"
cp "$media/sound/Voice/stakeout/jd - are we sure we have the right place.wav" "assets/sound/voice/stakeout/jd - are we sure we have the right place.wav"
cp "$media/sound/Voice/stakeout/jd - move in now.wav" "assets/sound/voice/stakeout/jd - move in now.wav"
cp "$media/sound/Voice/stakeout/jd - over there 1.wav" "assets/sound/voice/stakeout/jd - over there 1.wav"
cp "$media/sound/Voice/stakeout/jd - over there 2.wav" "assets/sound/voice/stakeout/jd - over there 2.wav"
cp "$media/sound/Voice/stakeout/jd - thats it take em down.wav" "assets/sound/voice/stakeout/jd - thats it take em down.wav"
cp "$media/sound/Voice/stakeout/jd - we have you surrounded.wav" "assets/sound/voice/stakeout/jd - we have you surrounded.wav"
cp "$media/sound/Voice/stakeout/most boring stakeout ever.wav" "assets/sound/voice/stakeout/most boring stakeout ever.wav"
cp "$media/sound/Voice/jd - im warning you.wav" "assets/sound/voice/tilt/jd - im warning you.wav"
cp "$media/sound/Voice/jd - put down your weapons.wav" "assets/sound/voice/tilt/jd - put down your weapons.wav"
cp "$media/sound/Voice/warning.wav" "assets/sound/voice/tilt/warning.wav"
cp "$media/sound/Voice/unused/civil unrest.wav" "assets/sound/voice/unused/civil unrest.wav"
cp "$media/sound/Voice/unused/crime 1.wav" "assets/sound/voice/unused/crime 1.wav"
cp "$media/sound/Voice/unused/i think you hit it.wav" "assets/sound/voice/unused/i think you hit it.wav"
cp "$media/sound/Voice/unused/jackpot - calm.wav" "assets/sound/voice/unused/jackpot - calm.wav"
cp "$media/sound/Voice/unused/jackpot slight excitement.wav" "assets/sound/voice/unused/jackpot slight excitement.wav"
cp "$media/sound/Voice/unused/jd - shoot the right ramp.wav" "assets/sound/voice/unused/jd - shoot the right ramp.wav"
cp "$media/sound/Voice/unused/lets order a pizza.wav" "assets/sound/voice/unused/lets order a pizza.wav"
cp "$media/sound/Voice/unused/shoot the right ramp.wav" "assets/sound/voice/unused/shoot the right ramp.wav"
cp "$media/sound/Voice/unused/shoot the super jackpot.wav" "assets/sound/voice/unused/shoot the super jackpot.wav"
cp "$media/sound/Voice/unused/super jackpot is lit.wav" "assets/sound/voice/unused/super jackpot is lit.wav"
cp "$media/sound/Voice/unused/super jackpot.wav" "assets/sound/voice/unused/super jackpot.wav"
cp "$media/sound/Voice/unused/the tank is down.wav" "assets/sound/voice/unused/the tank is down.wav"
cp "$media/sound/Voice/shooting_gallery/woman shot 1.wav" "assets/sound/voice/unused/woman shot 1.wav"
cp "$media/sound/Voice/shooting_gallery/woman shot 2.wav" "assets/sound/voice/unused/woman shot 2.wav"
cp "$media/sound/Voice/unused/youve just been promoted.wav" "assets/sound/voice/unused/youve just been promoted.wav"
cp "$media/sound/Voice/jd - reporting for duty.wav" "assets/sound/voice/welcome/jd - reporting for duty.wav"
cp "$media/sound/Voice/welcome.wav" "assets/sound/voice/welcome/welcome.wav"

